name: ytdlp-api

services:
  app:
    image: hackwae/ytdlp-api:latest
    container_name: ytdlp-api
    restart: unless-stopped

    ports:
      - "6001:6001"

    dns:
      - 1.1.1.1
      - 8.8.8.8

    environment:
      TZ: Asia/Makassar

    volumes:
      - type: bind
        source: /DATA/downloads
        target: /downloads

x-casaos:
  architectures:
    - amd64
    - arm64

  main: app

  category: HackWae-Appstore

  port_map: "6001"

  scheme: http

  index: /

  title:
    en_us: yt-dlp API

  description:
    en_us: Multi-platform downloader API with MP4, MP3, playlist and automation support.

  tagline:
    en_us: Downloader API for homelab automation

  developer: HackWae

  author: HackWae

  icon: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/main/Apps/icon/ytdlp.png

  thumbnail: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/main/Apps/icon/ytdlp.png

  tips:
    before_install:
      en_us: Make sure /DATA/downloads exists.

  store_app_id: ytdlp-api

  version: "1.0.0"